# Generated by Django 3.2 on 2021-10-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(default='male,female,', max_length=500),
        ),
    ]
