# Generated by Django 3.2 on 2021-10-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_shop', '0003_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(default='sex=male/female,', max_length=500),
        ),
    ]
